"""Proves migration 0010's hand-written DDL actually matches the ORM
models in app/modules/calculation/models.py — this migration was
hand-authored (not autogenerated, see its own docstring for why), so this
is the check that would catch a column/FK typo autogenerate would normally
catch for us.
"""

import datetime as dt
import uuid
from decimal import Decimal

import pytest
from sqlalchemy import select
from sqlalchemy.dialects.postgresql import Range
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.calculation.models import (
    BASIS_MODEL_IMPLIED,
    STATUS_APPROVED,
    CalculationInput,
    CalculationResult,
    CalculationSpecification,
    CalculationSupersession,
)
from app.modules.market.models import AcceptedFact


async def _seed_specification(session: AsyncSession, code: str) -> CalculationSpecification:
    spec = CalculationSpecification(
        code=code, version="v1", status=STATUS_APPROVED, description="test spec"
    )
    session.add(spec)
    await session.flush()
    return spec


async def _seed_accepted_fact(session: AsyncSession) -> AcceptedFact:
    fact = AcceptedFact(
        subject_type="INSTRUMENT",
        subject_id=uuid.uuid4(),
        metric_id="TEST_METRIC",
        valid_range=Range(lower=dt.datetime(2020, 1, 1, tzinfo=dt.UTC), upper=None, bounds="[)"),
        knowledge_range=Range(
            lower=dt.datetime.now(dt.UTC), upper=None, bounds="[)"
        ),
        value={"a": "1"},
        status="ACTIVE",
    )
    session.add(fact)
    await session.flush()
    return fact


async def test_calculation_specification_code_is_unique(db_session: AsyncSession) -> None:
    code = f"test-spec-{uuid.uuid4().hex[:8]}"
    await _seed_specification(db_session, code)
    await db_session.flush()

    db_session.add(
        CalculationSpecification(
            code=code, version="v2", status=STATUS_APPROVED, description="dup"
        )
    )
    with pytest.raises(IntegrityError):
        await db_session.flush()


async def test_calculation_result_round_trips_with_input_and_supersession(
    db_session: AsyncSession,
) -> None:
    spec = await _seed_specification(db_session, f"test-spec-{uuid.uuid4().hex[:8]}")
    fact = await _seed_accepted_fact(db_session)
    subject_id = uuid.uuid4()

    old_result = CalculationResult(
        calculation_specification_id=spec.id,
        subject_type="INSTRUMENT",
        subject_id=subject_id,
        metric_id="MODEL_IMPLIED_PRICE",
        as_of_date=dt.date(2026, 9, 1),
        basis=BASIS_MODEL_IMPLIED,
        value={"clean_price": "95.123456"},
        status="SUPERSEDED",
    )
    db_session.add(old_result)
    await db_session.flush()

    new_result = CalculationResult(
        calculation_specification_id=spec.id,
        subject_type="INSTRUMENT",
        subject_id=subject_id,
        metric_id="MODEL_IMPLIED_PRICE",
        as_of_date=dt.date(2026, 9, 1),
        basis=BASIS_MODEL_IMPLIED,
        value={"clean_price": "95.654321"},
        status="ACTIVE",
    )
    db_session.add(new_result)
    await db_session.flush()

    old_result.superseded_by_id = new_result.id

    db_session.add(
        CalculationInput(
            calculation_result_id=new_result.id, accepted_fact_id=fact.id, role="CURVE_POINT"
        )
    )
    db_session.add(
        CalculationSupersession(
            old_calculation_result_id=old_result.id,
            new_calculation_result_id=new_result.id,
            reason="curve updated",
        )
    )
    await db_session.flush()
    await db_session.commit()

    fetched = (
        await db_session.execute(
            select(CalculationResult).where(CalculationResult.subject_id == subject_id)
        )
    ).scalars().all()
    assert len(fetched) == 2
    active = next(r for r in fetched if r.status == "ACTIVE")
    assert active.value == {"clean_price": "95.654321"}
    assert Decimal(active.value["clean_price"]) == Decimal("95.654321")


async def test_calculation_input_requires_a_real_accepted_fact(db_session: AsyncSession) -> None:
    spec = await _seed_specification(db_session, f"test-spec-{uuid.uuid4().hex[:8]}")
    result = CalculationResult(
        calculation_specification_id=spec.id,
        subject_type="INSTRUMENT",
        subject_id=uuid.uuid4(),
        metric_id="MODEL_IMPLIED_PRICE",
        as_of_date=dt.date(2026, 9, 1),
        basis=BASIS_MODEL_IMPLIED,
        value={"clean_price": "100"},
        status="ACTIVE",
    )
    db_session.add(result)
    await db_session.flush()

    db_session.add(
        CalculationInput(
            calculation_result_id=result.id, accepted_fact_id=uuid.uuid4(), role="CURVE_POINT"
        )
    )
    with pytest.raises(IntegrityError):
        await db_session.flush()
