"""0003 governance rights and policy tables

rights_profile/jurisdiction_policy/capability_status/activation_record/
kill_switch are platform-wide governance objects (no account_id/principal_id)
so they get no RLS. policy_decision does carry (nullable) account_id/
principal_id and gets RLS — see the provisional policy below. It runs as
`talvrin_app` (0001's grants), the unprivileged role RLS actually applies
to; a dedicated ops-bypass role for reading decisions across accounts is
still a P2 SEC-001 item, so for now pre-auth decisions (both columns NULL)
are visible platform-wide by design rather than hidden behind a role that
doesn't exist yet. See 0002 for why the policy uses NULLIF(..., '') rather
than a bare cast on current_setting().

Revision ID: 06706311a718
Revises: 0df559156a42
Create Date: 2026-09-10 14:16:47.783582

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06706311a718"
down_revision: str | Sequence[str] | None = "0df559156a42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activation_record',
    sa.Column('jurisdiction_code', sa.String(length=8), nullable=False),
    sa.Column('operating_entity', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='governance'
    )
    op.create_index(op.f('ix_governance_activation_record_jurisdiction_code'), 'activation_record', ['jurisdiction_code'], unique=False, schema='governance')
    op.create_table('capability_status',
    sa.Column('capability_code', sa.String(length=120), nullable=False),
    sa.Column('jurisdiction_code', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='governance'
    )
    op.create_index(op.f('ix_governance_capability_status_capability_code'), 'capability_status', ['capability_code'], unique=False, schema='governance')
    op.create_table('jurisdiction_policy',
    sa.Column('jurisdiction_code', sa.String(length=8), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='governance'
    )
    op.create_index(op.f('ix_governance_jurisdiction_policy_jurisdiction_code'), 'jurisdiction_policy', ['jurisdiction_code'], unique=False, schema='governance')
    op.create_table('rights_profile',
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='governance'
    )
    op.create_table('kill_switch',
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_by_principal_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activated_by_principal_id'], ['identity.principal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='governance'
    )
    op.create_table('policy_decision',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_output_type', sa.String(length=64), nullable=True),
    sa.Column('obligations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['identity.account.id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['identity.principal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='governance'
    )
    op.create_index(op.f('ix_governance_policy_decision_account_id'), 'policy_decision', ['account_id'], unique=False, schema='governance')
    op.create_index(op.f('ix_governance_policy_decision_principal_id'), 'policy_decision', ['principal_id'], unique=False, schema='governance')
    op.create_index(op.f('ix_governance_policy_decision_request_id'), 'policy_decision', ['request_id'], unique=False, schema='governance')
    # ### end Alembic commands ###

    # --- Row-Level Security (hand-authored) ---
    op.execute("ALTER TABLE governance.policy_decision ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE governance.policy_decision FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY policy_decision_isolation ON governance.policy_decision
        USING (
            (account_id IS NULL AND principal_id IS NULL)
            OR (account_id IS NOT NULL AND account_id = NULLIF(current_setting('app.account_id', true), '')::uuid)
            OR (principal_id IS NOT NULL AND principal_id = NULLIF(current_setting('app.principal_id', true), '')::uuid)
        )
        WITH CHECK (
            (account_id IS NULL AND principal_id IS NULL)
            OR (account_id IS NOT NULL AND account_id = NULLIF(current_setting('app.account_id', true), '')::uuid)
            OR (principal_id IS NOT NULL AND principal_id = NULLIF(current_setting('app.principal_id', true), '')::uuid)
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS policy_decision_isolation ON governance.policy_decision")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_governance_policy_decision_request_id'), table_name='policy_decision', schema='governance')
    op.drop_index(op.f('ix_governance_policy_decision_principal_id'), table_name='policy_decision', schema='governance')
    op.drop_index(op.f('ix_governance_policy_decision_account_id'), table_name='policy_decision', schema='governance')
    op.drop_table('policy_decision', schema='governance')
    op.drop_table('kill_switch', schema='governance')
    op.drop_table('rights_profile', schema='governance')
    op.drop_index(op.f('ix_governance_jurisdiction_policy_jurisdiction_code'), table_name='jurisdiction_policy', schema='governance')
    op.drop_table('jurisdiction_policy', schema='governance')
    op.drop_index(op.f('ix_governance_capability_status_capability_code'), table_name='capability_status', schema='governance')
    op.drop_table('capability_status', schema='governance')
    op.drop_index(op.f('ix_governance_activation_record_jurisdiction_code'), table_name='activation_record', schema='governance')
    op.drop_table('activation_record', schema='governance')
    # ### end Alembic commands ###
