"""0002 identity and audit tables

RLS is enabled here, in the same migration that creates the table, per plan
§0 ("cheap now, expensive retrofitted"). Policies read the session-local
`app.account_id` / `app.principal_id` GUCs — set once per request by
app.modules.identity's auth dependency (P0 week 3+), mirroring the
contextvars in app.core.request_context. `FORCE ROW LEVEL SECURITY` is set
so RLS applies even to the table-owning `talvrin` role, since no separate
least-privileged app role exists yet (P2 hardening item).

Revision ID: 0df559156a42
Revises: f0477a8fb9fe
Create Date: 2026-09-10 14:15:42.287807

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0df559156a42"
down_revision: str | Sequence[str] | None = "f0477a8fb9fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('actor_principal_id', sa.UUID(), nullable=True),
    sa.Column('subject_type', sa.String(length=120), nullable=True),
    sa.Column('subject_id', sa.String(length=200), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_event_log_event_type'), 'event_log', ['event_type'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_event_log_occurred_at'), 'event_log', ['occurred_at'], unique=False, schema='audit')
    op.create_table('account',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_table('principal',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['identity.account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_principal_account_id'), 'principal', ['account_id'], unique=False, schema='identity')
    op.create_table('session',
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['identity.principal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_session_principal_id'), 'session', ['principal_id'], unique=False, schema='identity')
    # ### end Alembic commands ###

    # --- Row-Level Security (hand-authored; not part of autogenerate) ---
    #
    # NULLIF(current_setting(..., true), '') is required, not just tidy: once
    # a custom GUC has been set via set_config() anywhere in a session, later
    # reads in that same session return '' (not NULL) after the setting
    # transaction ends — casting ''::uuid raises a hard DB error instead of
    # the comparison failing closed. Confirmed live: a session that legitimately
    # never touches app.account_id gets NULL and fails closed cleanly; a
    # pooled connection that touched it earlier for a different request gets
    # ''. With connection pooling in play, the second case will happen in
    # production, so both must resolve to a clean "no rows", not a 500.
    op.execute("ALTER TABLE identity.principal ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE identity.principal FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY principal_isolation ON identity.principal
        USING (account_id = NULLIF(current_setting('app.account_id', true), '')::uuid)
        WITH CHECK (account_id = NULLIF(current_setting('app.account_id', true), '')::uuid)
        """
    )

    op.execute("ALTER TABLE identity.session ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE identity.session FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY session_isolation ON identity.session
        USING (principal_id = NULLIF(current_setting('app.principal_id', true), '')::uuid)
        WITH CHECK (principal_id = NULLIF(current_setting('app.principal_id', true), '')::uuid)
        """
    )
    # identity.account and audit.event_log are intentionally NOT RLS-scoped:
    # account is the tenant root (nothing to scope it against), and event_log
    # is written across principals/accounts by design (see
    # app.modules.audit.service.record_event) — access control for audit
    # reads belongs to a future ops-role check, not row-level policy.


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS session_isolation ON identity.session")
    op.execute("DROP POLICY IF EXISTS principal_isolation ON identity.principal")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_session_principal_id'), table_name='session', schema='identity')
    op.drop_table('session', schema='identity')
    op.drop_index(op.f('ix_identity_principal_account_id'), table_name='principal', schema='identity')
    op.drop_table('principal', schema='identity')
    op.drop_table('account', schema='identity')
    op.drop_index(op.f('ix_audit_event_log_occurred_at'), table_name='event_log', schema='audit')
    op.drop_index(op.f('ix_audit_event_log_event_type'), table_name='event_log', schema='audit')
    op.drop_table('event_log', schema='audit')
    # ### end Alembic commands ###
