"""0006 market ingestion schema

Ingestion-side only (source -> dataset -> source_artifact ->
source_observation). No RLS: platform-wide, not account-scoped.
source_observation.rights_profile_id has no FK constraint yet — see
app/modules/market/models.py's docstring for why.

Revision ID: 1d1e3a218618
Revises: a5bece9e714c
Create Date: 2026-09-11 11:19:05.634083

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d1e3a218618"
down_revision: str | Sequence[str] | None = "a5bece9e714c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='market'
    )
    op.create_table('dataset',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['market.source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='market'
    )
    op.create_index(op.f('ix_market_dataset_source_id'), 'dataset', ['source_id'], unique=False, schema='market')
    op.create_table('source_artifact',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_ref', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('byte_length', sa.Integer(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['market.dataset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='market'
    )
    op.create_index(op.f('ix_market_source_artifact_dataset_id'), 'source_artifact', ['dataset_id'], unique=False, schema='market')
    op.create_index(op.f('ix_market_source_artifact_sha256'), 'source_artifact', ['sha256'], unique=False, schema='market')
    op.create_table('source_observation',
    sa.Column('source_artifact_id', sa.UUID(), nullable=False),
    sa.Column('rights_profile_id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('metric_id', sa.String(length=64), nullable=False),
    sa.Column('semantic_observation_key', sa.String(length=128), nullable=False),
    sa.Column('raw_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['market.source_artifact.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semantic_observation_key'),
    schema='market'
    )
    op.create_index(op.f('ix_market_source_observation_metric_id'), 'source_observation', ['metric_id'], unique=False, schema='market')
    op.create_index(op.f('ix_market_source_observation_source_artifact_id'), 'source_observation', ['source_artifact_id'], unique=False, schema='market')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_source_observation_source_artifact_id'), table_name='source_observation', schema='market')
    op.drop_index(op.f('ix_market_source_observation_metric_id'), table_name='source_observation', schema='market')
    op.drop_table('source_observation', schema='market')
    op.drop_index(op.f('ix_market_source_artifact_sha256'), table_name='source_artifact', schema='market')
    op.drop_index(op.f('ix_market_source_artifact_dataset_id'), table_name='source_artifact', schema='market')
    op.drop_table('source_artifact', schema='market')
    op.drop_index(op.f('ix_market_dataset_source_id'), table_name='dataset', schema='market')
    op.drop_table('dataset', schema='market')
    op.drop_table('source', schema='market')
    # ### end Alembic commands ###
