"""0022 evidence document versioning

P4 EVID-001 E0 (core evidence object model): adds document_version and
parsed_document_version, closing the identity-key separation the spec
requires (DocumentID != DocumentVersionID != ParsedDocumentVersionID !=
SourceArtefactID). Repoints document_chunk at parsed_document_version
instead of document directly, since chunking is parser-version-specific
retrieval output (EVID-001 §11.2), not a document-level fact. Also adds
document_processing_job, mirroring calculation.calculation_job's identical
out-of-process-handoff shape.

document_chunk has never had a writer (evidence/service.py and monitoring/
alerts.py only ever construct FACT/CALCULATION EvidenceMembers so far), so
repointing its FK and renaming chunk_index -> ordinal is a pure DDL change,
not a backfill - there is no data to migrate.

Hand-written, not autogenerated - same reason as every other cross-schema
migration in this project (see the alembic-autogenerate-hazard lesson):
autogenerate diffs the full metadata and will propose touching unrelated
tables it doesn't understand the intent behind.

Revision ID: 1f979c36d507
Revises: 2cbe9c582ec6
Create Date: 2026-09-18 15:20:17.378563

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f979c36d507"
down_revision: str | Sequence[str] | None = "2cbe9c582ec6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "document_version",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("source_artifact_id", sa.UUID(), nullable=False),
        sa.Column("rights_profile_id", sa.UUID(), nullable=False),
        sa.Column("version_label", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["evidence.document.id"]),
        sa.ForeignKeyConstraint(["source_artifact_id"], ["market.source_artifact.id"]),
        sa.ForeignKeyConstraint(["rights_profile_id"], ["governance.rights_profile.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="evidence",
    )
    op.create_index(
        op.f("ix_evidence_document_version_document_id"), "document_version",
        ["document_id"], unique=False, schema="evidence",
    )
    op.create_index(
        op.f("ix_evidence_document_version_source_artifact_id"), "document_version",
        ["source_artifact_id"], unique=False, schema="evidence",
    )

    op.create_table(
        "parsed_document_version",
        sa.Column("document_version_id", sa.UUID(), nullable=False),
        sa.Column("parser_name", sa.String(length=100), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("parse_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parse_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "language_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False,
        ),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("extraction_quality", sa.String(length=16), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_version_id"], ["evidence.document_version.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="evidence",
    )
    op.create_index(
        op.f("ix_evidence_parsed_document_version_document_version_id"),
        "parsed_document_version", ["document_version_id"], unique=False, schema="evidence",
    )

    op.create_table(
        "document_processing_job",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["evidence.document.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="evidence",
    )
    op.create_index(
        op.f("ix_evidence_document_processing_job_document_id"), "document_processing_job",
        ["document_id"], unique=False, schema="evidence",
    )
    op.create_index(
        op.f("ix_evidence_document_processing_job_status"), "document_processing_job",
        ["status"], unique=False, schema="evidence",
    )

    # document_chunk: repoint at parsed_document_version, add the missing
    # EVID-001 §11.2 fields. Empty table, no data to migrate.
    op.drop_index(
        "ix_evidence_document_chunk_document_id", table_name="document_chunk",
        schema="evidence",
    )
    op.drop_constraint(
        "document_chunk_document_id_fkey", "document_chunk", schema="evidence",
        type_="foreignkey",
    )
    op.alter_column(
        "document_chunk", "document_id", new_column_name="parsed_document_version_id",
        schema="evidence",
    )
    op.alter_column(
        "document_chunk", "chunk_index", new_column_name="ordinal", schema="evidence",
    )
    op.add_column(
        "document_chunk", sa.Column("chunker_version", sa.String(length=32), nullable=False,
        server_default="unversioned"), schema="evidence",
    )
    op.alter_column("document_chunk", "chunker_version", server_default=None, schema="evidence")
    op.add_column(
        "document_chunk", sa.Column("page_start", sa.Integer(), nullable=True),
        schema="evidence",
    )
    op.add_column(
        "document_chunk", sa.Column("page_end", sa.Integer(), nullable=True), schema="evidence",
    )
    op.add_column(
        "document_chunk", sa.Column("token_estimate", sa.Integer(), nullable=True),
        schema="evidence",
    )
    op.add_column(
        "document_chunk", sa.Column("content_hash", sa.String(length=64), nullable=False,
        server_default=""), schema="evidence",
    )
    op.alter_column("document_chunk", "content_hash", server_default=None, schema="evidence")
    op.create_foreign_key(
        "document_chunk_parsed_document_version_id_fkey", "document_chunk",
        "parsed_document_version", ["parsed_document_version_id"], ["id"],
        source_schema="evidence", referent_schema="evidence",
    )
    op.create_index(
        op.f("ix_evidence_document_chunk_parsed_document_version_id"), "document_chunk",
        ["parsed_document_version_id"], unique=False, schema="evidence",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f("ix_evidence_document_chunk_parsed_document_version_id"),
        table_name="document_chunk", schema="evidence",
    )
    op.drop_constraint(
        "document_chunk_parsed_document_version_id_fkey", "document_chunk", schema="evidence",
        type_="foreignkey",
    )
    op.drop_column("document_chunk", "content_hash", schema="evidence")
    op.drop_column("document_chunk", "token_estimate", schema="evidence")
    op.drop_column("document_chunk", "page_end", schema="evidence")
    op.drop_column("document_chunk", "page_start", schema="evidence")
    op.drop_column("document_chunk", "chunker_version", schema="evidence")
    op.alter_column(
        "document_chunk", "ordinal", new_column_name="chunk_index", schema="evidence",
    )
    op.alter_column(
        "document_chunk", "parsed_document_version_id", new_column_name="document_id",
        schema="evidence",
    )
    op.create_foreign_key(
        "document_chunk_document_id_fkey", "document_chunk", "document",
        ["document_id"], ["id"], source_schema="evidence", referent_schema="evidence",
    )
    op.create_index(
        "ix_evidence_document_chunk_document_id", "document_chunk", ["document_id"],
        unique=False, schema="evidence",
    )

    op.drop_index(
        op.f("ix_evidence_document_processing_job_status"),
        table_name="document_processing_job", schema="evidence",
    )
    op.drop_index(
        op.f("ix_evidence_document_processing_job_document_id"),
        table_name="document_processing_job", schema="evidence",
    )
    op.drop_table("document_processing_job", schema="evidence")

    op.drop_index(
        op.f("ix_evidence_parsed_document_version_document_version_id"),
        table_name="parsed_document_version", schema="evidence",
    )
    op.drop_table("parsed_document_version", schema="evidence")

    op.drop_index(
        op.f("ix_evidence_document_version_source_artifact_id"),
        table_name="document_version", schema="evidence",
    )
    op.drop_index(
        op.f("ix_evidence_document_version_document_id"),
        table_name="document_version", schema="evidence",
    )
    op.drop_table("document_version", schema="evidence")
