"""0007 evidence schema

No RLS: platform-wide, not account-scoped. evidence_member.accepted_fact_id
and .calculation_result_id are intentionally FK-less — market.accepted_fact
(week 9) and calculation.calculation_result (week 11) don't exist yet; the
real FK constraints are ALTER TABLE'd on in those migrations.

Revision ID: 218d2d853eb1
Revises: 1d1e3a218618
Create Date: 2026-09-11 11:19:34.456926

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "218d2d853eb1"
down_revision: str | Sequence[str] | None = "1d1e3a218618"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='evidence'
    )
    op.create_table('evidence_bundle',
    sa.Column('purpose_type', sa.String(length=64), nullable=False),
    sa.Column('knowledge_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='evidence'
    )
    op.create_table('document_chunk',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['evidence.document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='evidence'
    )
    op.create_index(op.f('ix_evidence_document_chunk_document_id'), 'document_chunk', ['document_id'], unique=False, schema='evidence')
    op.create_table('citation_locator',
    sa.Column('document_chunk_id', sa.UUID(), nullable=False),
    sa.Column('locator_type', sa.String(length=32), nullable=False),
    sa.Column('locator_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['evidence.document_chunk.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='evidence'
    )
    op.create_index(op.f('ix_evidence_citation_locator_document_chunk_id'), 'citation_locator', ['document_chunk_id'], unique=False, schema='evidence')
    op.create_table('evidence_member',
    sa.Column('evidence_bundle_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('accepted_fact_id', sa.UUID(), nullable=True),
    sa.Column('calculation_result_id', sa.UUID(), nullable=True),
    sa.Column('document_chunk_id', sa.UUID(), nullable=True),
    sa.Column('citation_locator_id', sa.UUID(), nullable=True),
    sa.Column('source_artifact_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['citation_locator_id'], ['evidence.citation_locator.id'], ),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['evidence.document_chunk.id'], ),
    sa.ForeignKeyConstraint(['evidence_bundle_id'], ['evidence.evidence_bundle.id'], ),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['market.source_artifact.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='evidence'
    )
    op.create_index(op.f('ix_evidence_evidence_member_evidence_bundle_id'), 'evidence_member', ['evidence_bundle_id'], unique=False, schema='evidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_evidence_member_evidence_bundle_id'), table_name='evidence_member', schema='evidence')
    op.drop_table('evidence_member', schema='evidence')
    op.drop_index(op.f('ix_evidence_citation_locator_document_chunk_id'), table_name='citation_locator', schema='evidence')
    op.drop_table('citation_locator', schema='evidence')
    op.drop_index(op.f('ix_evidence_document_chunk_document_id'), table_name='document_chunk', schema='evidence')
    op.drop_table('document_chunk', schema='evidence')
    op.drop_table('evidence_bundle', schema='evidence')
    op.drop_table('document', schema='evidence')
    # ### end Alembic commands ###
