"""0018 evaluator heartbeat

Adds monitoring.evaluator_heartbeat - MON-001 §12.3's dead-man control.
Platform-wide operational data (no account_id/RLS), same reasoning as
governance.kill_switch: one row per named worker process, not per tenant.

Hand-written, not autogenerated - same reason as every other monitoring
migration this project has added.

Revision ID: 38fa495cbdf5
Revises: cbd0514a146e
Create Date: 2026-09-17 19:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38fa495cbdf5"
down_revision: str | Sequence[str] | None = "cbd0514a146e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "evaluator_heartbeat",
        sa.Column("worker_id", sa.String(length=64), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("worker_id"),
        schema="monitoring",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("evaluator_heartbeat", schema="monitoring")
