"""0008 accepted fact reconciliation and outbox

Closes two FKs deliberately deferred earlier (expand-contract, OPS-001):
evidence_member.accepted_fact_id (deferred in week 7) and
source_observation.rights_profile_id (deferred in week 7/8). Also adds the
bitemporal GiST exclusion constraint on accepted_fact — the real DB-level
enforcement that no two versions of the same (subject_id, metric_id) can
overlap on both valid_range and knowledge_range simultaneously
(ENG-ARCH-003 D-1). No RLS on any of these: all platform-wide market data.

Revision ID: 492acb132ee6
Revises: 218d2d853eb1
Create Date: 2026-09-11 16:33:50.350956

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "492acb132ee6"
down_revision: str | Sequence[str] | None = "218d2d853eb1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accepted_fact',
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.String(length=64), nullable=False),
    sa.Column('valid_range', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('knowledge_range', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='market'
    )
    op.create_index(op.f('ix_market_accepted_fact_metric_id'), 'accepted_fact', ['metric_id'], unique=False, schema='market')
    op.create_index(op.f('ix_market_accepted_fact_subject_id'), 'accepted_fact', ['subject_id'], unique=False, schema='market')
    op.create_table('outbox_event',
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='market'
    )
    op.create_table('reconciliation_decision',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('accepted_fact_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_fact_id'], ['market.accepted_fact.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='market'
    )
    op.create_index(op.f('ix_market_reconciliation_decision_metric_id'), 'reconciliation_decision', ['metric_id'], unique=False, schema='market')
    op.create_index(op.f('ix_market_reconciliation_decision_subject_id'), 'reconciliation_decision', ['subject_id'], unique=False, schema='market')
    op.create_table('fact_observation_link',
    sa.Column('accepted_fact_id', sa.UUID(), nullable=False),
    sa.Column('source_observation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_fact_id'], ['market.accepted_fact.id'], ),
    sa.ForeignKeyConstraint(['source_observation_id'], ['market.source_observation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='market'
    )
    op.create_index(op.f('ix_market_fact_observation_link_accepted_fact_id'), 'fact_observation_link', ['accepted_fact_id'], unique=False, schema='market')
    op.create_index(op.f('ix_market_fact_observation_link_source_observation_id'), 'fact_observation_link', ['source_observation_id'], unique=False, schema='market')
    op.create_foreign_key(
        'fk_evidence_member_accepted_fact',
        'evidence_member', 'accepted_fact', ['accepted_fact_id'], ['id'],
        source_schema='evidence', referent_schema='market',
    )
    op.create_foreign_key(
        'fk_source_observation_rights_profile',
        'source_observation', 'rights_profile', ['rights_profile_id'], ['id'],
        source_schema='market', referent_schema='governance',
    )
    # ### end Alembic commands ###

    # --- Bitemporal exclusion constraint (hand-authored) ---
    op.execute(
        """
        ALTER TABLE market.accepted_fact
        ADD CONSTRAINT accepted_fact_no_overlap
        EXCLUDE USING gist (
            subject_id WITH =,
            metric_id WITH =,
            valid_range WITH &&,
            knowledge_range WITH &&
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE market.accepted_fact DROP CONSTRAINT accepted_fact_no_overlap")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_source_observation_rights_profile', 'source_observation',
        schema='market', type_='foreignkey',
    )
    op.drop_constraint(
        'fk_evidence_member_accepted_fact', 'evidence_member',
        schema='evidence', type_='foreignkey',
    )
    op.drop_index(op.f('ix_market_fact_observation_link_source_observation_id'), table_name='fact_observation_link', schema='market')
    op.drop_index(op.f('ix_market_fact_observation_link_accepted_fact_id'), table_name='fact_observation_link', schema='market')
    op.drop_table('fact_observation_link', schema='market')
    op.drop_index(op.f('ix_market_reconciliation_decision_subject_id'), table_name='reconciliation_decision', schema='market')
    op.drop_index(op.f('ix_market_reconciliation_decision_metric_id'), table_name='reconciliation_decision', schema='market')
    op.drop_table('reconciliation_decision', schema='market')
    op.drop_table('outbox_event', schema='market')
    op.drop_index(op.f('ix_market_accepted_fact_subject_id'), table_name='accepted_fact', schema='market')
    op.drop_index(op.f('ix_market_accepted_fact_metric_id'), table_name='accepted_fact', schema='market')
    op.drop_table('accepted_fact', schema='market')
    # ### end Alembic commands ###
