"""0015 monitoring alerts

Adds monitoring.alert - MON-001 §13.1, trimmed to this slice's implemented
fields (see app/modules/monitoring/models.py's docstring for exactly what's
deferred: delivery-related status values, unit/valid_time/
input_freshness_state). One alert per evaluation at most (evaluation_id is
unique), per §19.1's own DB-constraint note.

Alerts are user-owned like every other monitoring table - real Postgres
RLS in this same migration, same as 0014.

Hand-written, not autogenerated - same reason as every other calculation/
monitoring migration this project has added (autogenerate currently
proposes dropping identity's password_hash/token_hash columns).

Revision ID: 7501ba01d29b
Revises: 8083d877d010
Create Date: 2026-09-17 16:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7501ba01d29b"
down_revision: str | Sequence[str] | None = "8083d877d010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "alert",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("rule_version_id", sa.UUID(), nullable=False),
        sa.Column("evaluation_id", sa.UUID(), nullable=False),
        sa.Column("alert_type", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("metric_id", sa.String(length=64), nullable=False),
        sa.Column("observed_value", sa.Numeric(20, 8), nullable=False),
        sa.Column("threshold_value", sa.Numeric(20, 8), nullable=False),
        sa.Column("knowledge_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_bundle_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["monitoring.monitoring_rule.id"], name="fk_alert_monitoring_rule",
        ),
        sa.ForeignKeyConstraint(
            ["rule_version_id"], ["monitoring.monitoring_rule_version.id"],
            name="fk_alert_monitoring_rule_version",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"], ["monitoring.rule_evaluation.id"], name="fk_alert_rule_evaluation",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_bundle_id"], ["evidence.evidence_bundle.id"],
            name="fk_alert_evidence_bundle",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evaluation_id"),
        schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_alert_account_id"), "alert", ["account_id"], unique=False,
        schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_alert_rule_id"), "alert", ["rule_id"], unique=False,
        schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_alert_rule_version_id"), "alert", ["rule_version_id"], unique=False,
        schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_alert_subject_id"), "alert", ["subject_id"], unique=False,
        schema="monitoring",
    )

    op.execute("ALTER TABLE monitoring.alert ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE monitoring.alert FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY alert_isolation ON monitoring.alert
        USING (account_id = NULLIF(current_setting('app.account_id', true), '')::uuid)
        WITH CHECK (account_id = NULLIF(current_setting('app.account_id', true), '')::uuid)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS alert_isolation ON monitoring.alert")
    op.drop_index(op.f("ix_monitoring_alert_subject_id"), table_name="alert", schema="monitoring")
    op.drop_index(
        op.f("ix_monitoring_alert_rule_version_id"), table_name="alert", schema="monitoring"
    )
    op.drop_index(op.f("ix_monitoring_alert_rule_id"), table_name="alert", schema="monitoring")
    op.drop_index(op.f("ix_monitoring_alert_account_id"), table_name="alert", schema="monitoring")
    op.drop_table("alert", schema="monitoring")
