"""0014 monitoring rules and evaluations

Adds monitoring.monitoring_rule / monitoring_rule_version / rule_evaluation
/ rule_evaluation_input — P3's first slice (PLT-MON-001): a rule can be
defined and evaluated once. Alerts, delivery, coverage tracking and the
dead-man watcher are separate, later migrations - see
app/modules/monitoring/models.py's docstring for exactly which
MON-001-specified fields this slice deliberately does not model yet.

Rules are user-owned data (unlike reference/calculation), so every table
here gets real Postgres RLS in this same migration - "enable it where the
table is created, not retrofitted" (the lesson already applied to
identity.principal/session, governance.policy_decision and every
research.* table).

Hand-written, not autogenerated - same reason as migrations 0010 and 0013:
this project's autogenerate run currently proposes dropping identity's
password_hash/token_hash columns (never modelled in the ORM on purpose).

Revision ID: 8083d877d010
Revises: 848e6d059072
Create Date: 2026-09-17 15:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8083d877d010"
down_revision: str | Sequence[str] | None = "848e6d059072"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ACCOUNT_SCOPED_TABLES = (
    "monitoring_rule",
    "monitoring_rule_version",
    "rule_evaluation",
    "rule_evaluation_input",
)


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "monitoring_rule",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("current_rule_version_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_monitoring_rule_account_id"),
        "monitoring_rule", ["account_id"], unique=False, schema="monitoring",
    )

    op.create_table(
        "monitoring_rule_version",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("metric_id", sa.String(length=64), nullable=False),
        sa.Column("predicate", sa.String(length=32), nullable=False),
        sa.Column("threshold_value", sa.Numeric(20, 8), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_principal_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["monitoring.monitoring_rule.id"],
            name="fk_monitoring_rule_version_monitoring_rule",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_monitoring_rule_version_account_id"),
        "monitoring_rule_version", ["account_id"], unique=False, schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_monitoring_rule_version_rule_id"),
        "monitoring_rule_version", ["rule_id"], unique=False, schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_monitoring_rule_version_subject_id"),
        "monitoring_rule_version", ["subject_id"], unique=False, schema="monitoring",
    )

    op.create_table(
        "rule_evaluation",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("evaluation_key", sa.String(length=128), nullable=False),
        sa.Column("rule_version_id", sa.UUID(), nullable=False),
        sa.Column("trigger_type", sa.String(length=32), nullable=False),
        sa.Column("trigger_id", sa.UUID(), nullable=True),
        sa.Column("knowledge_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evaluator_version", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column(
            "evaluated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_version_id"], ["monitoring.monitoring_rule_version.id"],
            name="fk_rule_evaluation_monitoring_rule_version",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evaluation_key"),
        schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_rule_evaluation_account_id"),
        "rule_evaluation", ["account_id"], unique=False, schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_rule_evaluation_rule_version_id"),
        "rule_evaluation", ["rule_version_id"], unique=False, schema="monitoring",
    )

    op.create_table(
        "rule_evaluation_input",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("rule_evaluation_id", sa.UUID(), nullable=False),
        sa.Column("accepted_fact_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_evaluation_id"], ["monitoring.rule_evaluation.id"],
            name="fk_rule_evaluation_input_rule_evaluation",
        ),
        sa.ForeignKeyConstraint(
            ["accepted_fact_id"], ["market.accepted_fact.id"],
            name="fk_rule_evaluation_input_accepted_fact",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_rule_evaluation_input_account_id"),
        "rule_evaluation_input", ["account_id"], unique=False, schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_rule_evaluation_input_rule_evaluation_id"),
        "rule_evaluation_input", ["rule_evaluation_id"], unique=False, schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_rule_evaluation_input_accepted_fact_id"),
        "rule_evaluation_input", ["accepted_fact_id"], unique=False, schema="monitoring",
    )

    # --- row level security -------------------------------------------------
    # NULLIF(current_setting(..., true), '') rather than a bare cast: see
    # migration 0002 - a pooled connection that set the GUC for an earlier
    # request reads '' afterwards, and ''::uuid is a hard error, not a
    # clean "no rows".
    for table in _ACCOUNT_SCOPED_TABLES:
        op.execute(f"ALTER TABLE monitoring.{table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE monitoring.{table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_isolation ON monitoring.{table}
            USING (account_id = NULLIF(current_setting('app.account_id', true), '')::uuid)
            WITH CHECK (account_id = NULLIF(current_setting('app.account_id', true), '')::uuid)
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in _ACCOUNT_SCOPED_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {table}_isolation ON monitoring.{table}")

    op.drop_index(
        op.f("ix_monitoring_rule_evaluation_input_accepted_fact_id"),
        table_name="rule_evaluation_input", schema="monitoring",
    )
    op.drop_index(
        op.f("ix_monitoring_rule_evaluation_input_rule_evaluation_id"),
        table_name="rule_evaluation_input", schema="monitoring",
    )
    op.drop_index(
        op.f("ix_monitoring_rule_evaluation_input_account_id"),
        table_name="rule_evaluation_input", schema="monitoring",
    )
    op.drop_table("rule_evaluation_input", schema="monitoring")

    op.drop_index(
        op.f("ix_monitoring_rule_evaluation_rule_version_id"),
        table_name="rule_evaluation", schema="monitoring",
    )
    op.drop_index(
        op.f("ix_monitoring_rule_evaluation_account_id"),
        table_name="rule_evaluation", schema="monitoring",
    )
    op.drop_table("rule_evaluation", schema="monitoring")

    op.drop_index(
        op.f("ix_monitoring_monitoring_rule_version_subject_id"),
        table_name="monitoring_rule_version", schema="monitoring",
    )
    op.drop_index(
        op.f("ix_monitoring_monitoring_rule_version_rule_id"),
        table_name="monitoring_rule_version", schema="monitoring",
    )
    op.drop_index(
        op.f("ix_monitoring_monitoring_rule_version_account_id"),
        table_name="monitoring_rule_version", schema="monitoring",
    )
    op.drop_table("monitoring_rule_version", schema="monitoring")

    op.drop_index(
        op.f("ix_monitoring_monitoring_rule_account_id"),
        table_name="monitoring_rule", schema="monitoring",
    )
    op.drop_table("monitoring_rule", schema="monitoring")
