"""0013 calculation job queue

Adds calculation.calculation_job - the P2 "calculation_supersession rerun
flow" plan item's other half: a real job-table handoff so a real
out-of-process worker (scripts/run_calculation_worker.py) claims and runs
pricing work, instead of a request/ingest path calling
compute_and_persist_model_implied_price synchronously in-process. See
app/modules/calculation/pipeline/job_queue.py's docstring for why this
table's shape (status/attempts/last_error, claimed via `FOR UPDATE SKIP
LOCKED`) is deliberately a plain Postgres queue, not a message broker -
this pack is nowhere near the ~5,000 events/min threshold that would
justify one (ENG-ARCH-003 risk #7).

Hand-written, not autogenerated - same reason as migration 0010
(dc5d1ca5a93d): this project's autogenerate run currently proposes
dropping identity's password_hash/token_hash columns (never modelled in
the ORM on purpose), and a blind autogenerate would apply that diff too.

Revision ID: 848e6d059072
Revises: a1f3c9b7e2d4
Create Date: 2026-09-17 12:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "848e6d059072"
down_revision: str | Sequence[str] | None = "a1f3c9b7e2d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "calculation_job",
        sa.Column("calculation_specification_id", sa.UUID(), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="PENDING"),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["calculation_specification_id"],
            ["calculation.calculation_specification.id"],
            name="fk_calculation_job_calculation_specification",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="calculation",
    )
    op.create_index(
        op.f("ix_calculation_calculation_job_status"),
        "calculation_job", ["status"], unique=False, schema="calculation",
    )
    op.create_index(
        op.f("ix_calculation_calculation_job_subject_id"),
        "calculation_job", ["subject_id"], unique=False, schema="calculation",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f("ix_calculation_calculation_job_subject_id"),
        table_name="calculation_job", schema="calculation",
    )
    op.drop_index(
        op.f("ix_calculation_calculation_job_status"),
        table_name="calculation_job", schema="calculation",
    )
    op.drop_table("calculation_job", schema="calculation")
