"""0019 rule version rearm threshold

Adds monitoring.monitoring_rule_version.rearm_threshold - MON-001 §8's
hysteresis/re-arm control, modelled exactly as the spec's own worked
example does: a second absolute threshold (not a percentage/margin), that
a value must pass back through after a fire before a new crossing counts
as a fresh MATCH. Nullable: unset means no hysteresis, and a rule fires on
every raw crossing exactly as before this migration - §8.2 gives no
default margin ("must not encode an investment view... the user must
explicitly choose it"), so there is no sensible non-null default.

Hand-written, not autogenerated - same reason as every other monitoring
migration this project has added.

Revision ID: a0f5172cae50
Revises: 38fa495cbdf5
Create Date: 2026-09-18 09:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0f5172cae50"
down_revision: str | Sequence[str] | None = "38fa495cbdf5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "monitoring_rule_version",
        sa.Column("rearm_threshold", sa.Numeric(20, 8), nullable=True),
        schema="monitoring",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("monitoring_rule_version", "rearm_threshold", schema="monitoring")
