"""0012 evidence_bundle research_message_id link

Adds a nullable evidence.evidence_bundle.research_message_id column so
GET /research/{message_id}/evidence (P1 week 13) can look up the evidence
that backed a given assistant reply. Deliberately NOT an FK to
research.message: that table is raw-SQL-managed by the research module
(encrypted content, its own migration/ownership), and evidence.* must
never take on a cross-schema dependency on a table it doesn't own the
lifecycle of — the same reasoning evidence_member's own FK-less columns
used before their targets existed (see migration 0007's docstring).

Hand-written, not autogenerated - see memory "talvrin-alembic-autogenerate-
hazard": autogenerate currently proposes dropping the auth module's
password_hash/token_hash columns, so a blind `alembic revision
--autogenerate` diff is not safe to apply as-is on this project.

Revision ID: a1f3c9b7e2d4
Revises: c7e4a1b9d602
Create Date: 2026-09-16
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a1f3c9b7e2d4"
down_revision: str | Sequence[str] | None = "c7e4a1b9d602"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "evidence_bundle",
        sa.Column("research_message_id", sa.UUID(), nullable=True),
        schema="evidence",
    )
    op.create_index(
        "ix_evidence_bundle_research_message_id",
        "evidence_bundle",
        ["research_message_id"],
        schema="evidence",
    )


def downgrade() -> None:
    op.drop_index(
        "ix_evidence_bundle_research_message_id",
        table_name="evidence_bundle",
        schema="evidence",
    )
    op.drop_column("evidence_bundle", "research_message_id", schema="evidence")
