"""0005 reference schema tables

Platform-wide canonical registry (no account_id/principal_id) — no RLS here.

Revision ID: a5bece9e714c
Revises: e0a0c9eaebc8
Create Date: 2026-09-10 16:33:20.671551

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5bece9e714c"
down_revision: str | Sequence[str] | None = "e0a0c9eaebc8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issuer',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('instrument',
    sa.Column('issuer_id', sa.UUID(), nullable=False),
    sa.Column('instrument_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['reference.issuer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_index(op.f('ix_reference_instrument_instrument_type'), 'instrument', ['instrument_type'], unique=False, schema='reference')
    op.create_index(op.f('ix_reference_instrument_issuer_id'), 'instrument', ['issuer_id'], unique=False, schema='reference')
    op.create_table('issuer_alias',
    sa.Column('issuer_id', sa.UUID(), nullable=False),
    sa.Column('alias_type', sa.String(length=32), nullable=False),
    sa.Column('alias_value', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['reference.issuer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_type', 'alias_value', name='uq_issuer_alias_type_value'),
    schema='reference'
    )
    op.create_index(op.f('ix_reference_issuer_alias_issuer_id'), 'issuer_alias', ['issuer_id'], unique=False, schema='reference')
    op.create_table('fi_sovereign_terms',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('coupon_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('coupon_frequency', sa.String(length=16), nullable=False),
    sa.Column('day_count_convention', sa.String(length=32), nullable=False),
    sa.Column('first_issue_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('ex_dividend_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['reference.instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id'),
    schema='reference'
    )
    op.create_table('instrument_alias',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('alias_type', sa.String(length=32), nullable=False),
    sa.Column('alias_value', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['reference.instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_type', 'alias_value', name='uq_instrument_alias_type_value'),
    schema='reference'
    )
    op.create_index(op.f('ix_reference_instrument_alias_instrument_id'), 'instrument_alias', ['instrument_id'], unique=False, schema='reference')
    op.create_table('instrument_listing',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('venue_code', sa.String(length=32), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['reference.instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_index(op.f('ix_reference_instrument_listing_instrument_id'), 'instrument_listing', ['instrument_id'], unique=False, schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_instrument_listing_instrument_id'), table_name='instrument_listing', schema='reference')
    op.drop_table('instrument_listing', schema='reference')
    op.drop_index(op.f('ix_reference_instrument_alias_instrument_id'), table_name='instrument_alias', schema='reference')
    op.drop_table('instrument_alias', schema='reference')
    op.drop_table('fi_sovereign_terms', schema='reference')
    op.drop_index(op.f('ix_reference_issuer_alias_issuer_id'), table_name='issuer_alias', schema='reference')
    op.drop_table('issuer_alias', schema='reference')
    op.drop_index(op.f('ix_reference_instrument_issuer_id'), table_name='instrument', schema='reference')
    op.drop_index(op.f('ix_reference_instrument_instrument_type'), table_name='instrument', schema='reference')
    op.drop_table('instrument', schema='reference')
    op.drop_table('issuer', schema='reference')
    # ### end Alembic commands ###
