"""0017 monitoring coverage

Adds monitoring.monitoring_coverage / monitoring_coverage_incident -
MON-001 §12's "is this rule actually being evaluated on schedule" tracking
(see app/modules/monitoring/models.py's docstring for the four-state
ladder and why expected_evaluation_interval comes from market.freshness
rather than a new per-rule config column). The dead-man watcher itself
(§12.3) is not part of this migration - it needs a genuinely separate
process/deployment, not more schema.

User-owned like every other monitoring table - real Postgres RLS in this
same migration.

Hand-written, not autogenerated - same reason as every other monitoring/
calculation migration this project has added.

Revision ID: cbd0514a146e
Revises: e438103db17a
Create Date: 2026-09-17 18:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbd0514a146e"
down_revision: str | Sequence[str] | None = "e438103db17a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ACCOUNT_SCOPED_TABLES = ("monitoring_coverage", "monitoring_coverage_incident")


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "monitoring_coverage",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("current_rule_version_id", sa.UUID(), nullable=False),
        sa.Column("last_successful_evaluation_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_evaluation_outcome", sa.String(length=32), nullable=True),
        sa.Column("coverage_state", sa.String(length=16), nullable=False),
        sa.Column("lapse_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_incident_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["monitoring.monitoring_rule.id"],
            name="fk_monitoring_coverage_monitoring_rule",
        ),
        sa.ForeignKeyConstraint(
            ["current_rule_version_id"], ["monitoring.monitoring_rule_version.id"],
            name="fk_monitoring_coverage_monitoring_rule_version",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_id"),
        schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_monitoring_coverage_account_id"),
        "monitoring_coverage", ["account_id"], unique=False, schema="monitoring",
    )

    op.create_table(
        "monitoring_coverage_incident",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["monitoring.monitoring_rule.id"],
            name="fk_monitoring_coverage_incident_monitoring_rule",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_monitoring_coverage_incident_account_id"),
        "monitoring_coverage_incident", ["account_id"], unique=False, schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_monitoring_coverage_incident_rule_id"),
        "monitoring_coverage_incident", ["rule_id"], unique=False, schema="monitoring",
    )

    for table in _ACCOUNT_SCOPED_TABLES:
        op.execute(f"ALTER TABLE monitoring.{table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE monitoring.{table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_isolation ON monitoring.{table}
            USING (account_id = NULLIF(current_setting('app.account_id', true), '')::uuid)
            WITH CHECK (account_id = NULLIF(current_setting('app.account_id', true), '')::uuid)
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in _ACCOUNT_SCOPED_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {table}_isolation ON monitoring.{table}")

    op.drop_index(
        op.f("ix_monitoring_monitoring_coverage_incident_rule_id"),
        table_name="monitoring_coverage_incident", schema="monitoring",
    )
    op.drop_index(
        op.f("ix_monitoring_monitoring_coverage_incident_account_id"),
        table_name="monitoring_coverage_incident", schema="monitoring",
    )
    op.drop_table("monitoring_coverage_incident", schema="monitoring")

    op.drop_index(
        op.f("ix_monitoring_monitoring_coverage_account_id"),
        table_name="monitoring_coverage", schema="monitoring",
    )
    op.drop_table("monitoring_coverage", schema="monitoring")
