"""0010 calculation schema

Adds calculation.calculation_specification / calculation_result /
calculation_input / calculation_supersession — everything Talvrin computes,
as distinct from what it observes/reconciles (market.accepted_fact). See
app/modules/calculation/models.py's docstring for why the split matters.

Hand-written rather than autogenerated: this project's alembic env.py
was missing an import for app.modules.calculation.models until this
change, AND identity.principal/session carry password_hash/token_hash/
idle_expires_at columns (added directly via migration 0009, deliberately
NOT modelled in identity/models.py — see that migration's own docstring
for why: keeping password hashes out of the ORM keeps them out of query
logs). Together, an autogenerate run right now would have proposed
DROPPING those three columns as spurious "detected removed" diffs. Future
autogenerate runs will hit the same drift for identity.* every time until
that gap is closed some other way (e.g. a text-only migration test) - it
is not something this migration fixes, just something it deliberately
does not blindly apply.

Revision ID: dc5d1ca5a93d
Revises: b41c7f2ad905
Create Date: 2026-09-15 18:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc5d1ca5a93d"
down_revision: str | Sequence[str] | None = "b41c7f2ad905"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "calculation_specification",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        schema="calculation",
    )

    op.create_table(
        "calculation_result",
        sa.Column("calculation_specification_id", sa.UUID(), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("metric_id", sa.String(length=64), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("basis", sa.String(length=32), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("superseded_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["calculation_specification_id"],
            ["calculation.calculation_specification.id"],
            name="fk_calculation_result_calculation_specification",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="calculation",
    )
    op.create_index(
        op.f("ix_calculation_calculation_result_calculation_specification_id"),
        "calculation_result", ["calculation_specification_id"], unique=False,
        schema="calculation",
    )
    op.create_index(
        op.f("ix_calculation_calculation_result_metric_id"),
        "calculation_result", ["metric_id"], unique=False, schema="calculation",
    )
    op.create_index(
        op.f("ix_calculation_calculation_result_subject_id"),
        "calculation_result", ["subject_id"], unique=False, schema="calculation",
    )

    op.create_table(
        "calculation_input",
        sa.Column("calculation_result_id", sa.UUID(), nullable=False),
        sa.Column("accepted_fact_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["calculation_result_id"],
            ["calculation.calculation_result.id"],
            name="fk_calculation_input_calculation_result",
        ),
        sa.ForeignKeyConstraint(
            ["accepted_fact_id"],
            ["market.accepted_fact.id"],
            name="fk_calculation_input_accepted_fact",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="calculation",
    )
    op.create_index(
        op.f("ix_calculation_calculation_input_accepted_fact_id"),
        "calculation_input", ["accepted_fact_id"], unique=False, schema="calculation",
    )
    op.create_index(
        op.f("ix_calculation_calculation_input_calculation_result_id"),
        "calculation_input", ["calculation_result_id"], unique=False, schema="calculation",
    )

    op.create_table(
        "calculation_supersession",
        sa.Column("old_calculation_result_id", sa.UUID(), nullable=False),
        sa.Column("new_calculation_result_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["old_calculation_result_id"],
            ["calculation.calculation_result.id"],
            name="fk_calculation_supersession_old_result",
        ),
        sa.ForeignKeyConstraint(
            ["new_calculation_result_id"],
            ["calculation.calculation_result.id"],
            name="fk_calculation_supersession_new_result",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="calculation",
    )
    op.create_index(
        op.f("ix_calculation_calculation_supersession_new_calculation_result_id"),
        "calculation_supersession", ["new_calculation_result_id"], unique=False,
        schema="calculation",
    )
    op.create_index(
        op.f("ix_calculation_calculation_supersession_old_calculation_result_id"),
        "calculation_supersession", ["old_calculation_result_id"], unique=False,
        schema="calculation",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f("ix_calculation_calculation_supersession_old_calculation_result_id"),
        table_name="calculation_supersession", schema="calculation",
    )
    op.drop_index(
        op.f("ix_calculation_calculation_supersession_new_calculation_result_id"),
        table_name="calculation_supersession", schema="calculation",
    )
    op.drop_table("calculation_supersession", schema="calculation")

    op.drop_index(
        op.f("ix_calculation_calculation_input_calculation_result_id"),
        table_name="calculation_input", schema="calculation",
    )
    op.drop_index(
        op.f("ix_calculation_calculation_input_accepted_fact_id"),
        table_name="calculation_input", schema="calculation",
    )
    op.drop_table("calculation_input", schema="calculation")

    op.drop_index(
        op.f("ix_calculation_calculation_result_subject_id"),
        table_name="calculation_result", schema="calculation",
    )
    op.drop_index(
        op.f("ix_calculation_calculation_result_metric_id"),
        table_name="calculation_result", schema="calculation",
    )
    op.drop_index(
        op.f("ix_calculation_calculation_result_calculation_specification_id"),
        table_name="calculation_result", schema="calculation",
    )
    op.drop_table("calculation_result", schema="calculation")

    op.drop_table("calculation_specification", schema="calculation")
