"""0004 rights grant table

Platform-wide governance data (no account_id/principal_id), like its parent
rights_profile — no RLS here.

Revision ID: e0a0c9eaebc8
Revises: 06706311a718
Create Date: 2026-09-10 15:48:38.677010

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0a0c9eaebc8"
down_revision: str | Sequence[str] | None = "06706311a718"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rights_grant',
    sa.Column('rights_profile_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('permission_state', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rights_profile_id'], ['governance.rights_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rights_profile_id', 'action', name='uq_rights_grant_profile_action'),
    schema='governance'
    )
    op.create_index(op.f('ix_governance_rights_grant_rights_profile_id'), 'rights_grant', ['rights_profile_id'], unique=False, schema='governance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_governance_rights_grant_rights_profile_id'), table_name='rights_grant', schema='governance')
    op.drop_table('rights_grant', schema='governance')
    # ### end Alembic commands ###
