"""0016 alert delivery attempts

Adds monitoring.alert_delivery_attempt - MON-001 §14's at-least-once
delivery record, for this slice's one transport (IN_APP - see
app/modules/monitoring/models.py's docstring for why real push transports
and the retry policy are separate, later slices).

User-owned like every other monitoring table - real Postgres RLS in this
same migration.

Hand-written, not autogenerated - same reason as every other monitoring/
calculation migration this project has added.

Revision ID: e438103db17a
Revises: 7501ba01d29b
Create Date: 2026-09-17 17:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e438103db17a"
down_revision: str | Sequence[str] | None = "7501ba01d29b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "alert_delivery_attempt",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("alert_id", sa.UUID(), nullable=False),
        sa.Column("transport", sa.String(length=16), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column(
            "attempted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"], ["monitoring.alert.id"], name="fk_alert_delivery_attempt_alert",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_alert_delivery_attempt_account_id"),
        "alert_delivery_attempt", ["account_id"], unique=False, schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_alert_delivery_attempt_alert_id"),
        "alert_delivery_attempt", ["alert_id"], unique=False, schema="monitoring",
    )

    op.execute("ALTER TABLE monitoring.alert_delivery_attempt ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE monitoring.alert_delivery_attempt FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY alert_delivery_attempt_isolation ON monitoring.alert_delivery_attempt
        USING (account_id = NULLIF(current_setting('app.account_id', true), '')::uuid)
        WITH CHECK (account_id = NULLIF(current_setting('app.account_id', true), '')::uuid)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DROP POLICY IF EXISTS alert_delivery_attempt_isolation "
        "ON monitoring.alert_delivery_attempt"
    )
    op.drop_index(
        op.f("ix_monitoring_alert_delivery_attempt_alert_id"),
        table_name="alert_delivery_attempt", schema="monitoring",
    )
    op.drop_index(
        op.f("ix_monitoring_alert_delivery_attempt_account_id"),
        table_name="alert_delivery_attempt", schema="monitoring",
    )
    op.drop_table("alert_delivery_attempt", schema="monitoring")
