"""0020 debounce and alert suppression

Adds monitoring.monitoring_rule_version.debounce_seconds and
monitoring.alert_suppression - the other half of MON-001 §8 (hysteresis/
rearm landed in migration 0019). debounce_seconds defaults to 0 (no
debounce) - §8.2 gives no default duration and explicitly forbids a
default that would silently change a rule's economic meaning.

alert_suppression is user-owned like every other monitoring table - real
Postgres RLS in this same migration. Only the DEBOUNCE suppression reason
is used by this slice's code; the column itself is unconstrained (matches
MON-001's own enum: DEBOUNCE | QUIET_HOURS | RATE_LIMIT | FLAPPING |
DIGEST) so later slices can write the others without another migration.

Hand-written, not autogenerated - same reason as every other monitoring
migration this project has added.

Revision ID: f9d2e2c8716c
Revises: a0f5172cae50
Create Date: 2026-09-18 10:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9d2e2c8716c"
down_revision: str | Sequence[str] | None = "a0f5172cae50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "monitoring_rule_version",
        sa.Column("debounce_seconds", sa.Integer(), nullable=False, server_default="0"),
        schema="monitoring",
    )

    op.create_table(
        "alert_suppression",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("alert_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("policy_version", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_via_alert_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"], ["monitoring.alert.id"], name="fk_alert_suppression_alert",
        ),
        sa.ForeignKeyConstraint(
            ["released_via_alert_id"], ["monitoring.alert.id"],
            name="fk_alert_suppression_released_via_alert",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_alert_suppression_account_id"),
        "alert_suppression", ["account_id"], unique=False, schema="monitoring",
    )
    op.create_index(
        op.f("ix_monitoring_alert_suppression_alert_id"),
        "alert_suppression", ["alert_id"], unique=False, schema="monitoring",
    )

    op.execute("ALTER TABLE monitoring.alert_suppression ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE monitoring.alert_suppression FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY alert_suppression_isolation ON monitoring.alert_suppression
        USING (account_id = NULLIF(current_setting('app.account_id', true), '')::uuid)
        WITH CHECK (account_id = NULLIF(current_setting('app.account_id', true), '')::uuid)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DROP POLICY IF EXISTS alert_suppression_isolation ON monitoring.alert_suppression"
    )
    op.drop_index(
        op.f("ix_monitoring_alert_suppression_alert_id"),
        table_name="alert_suppression", schema="monitoring",
    )
    op.drop_index(
        op.f("ix_monitoring_alert_suppression_account_id"),
        table_name="alert_suppression", schema="monitoring",
    )
    op.drop_table("alert_suppression", schema="monitoring")
    op.drop_column("monitoring_rule_version", "debounce_seconds", schema="monitoring")
